SELECT "" AS Duplicate, 
    [CORP02WK]![Style] & [CORP02WK]![Color] AS [KEY], CORP02WK.[Core Code], 
    CORP02WK.[Supplier Number], 
    Diver.[Plant Code], 
    Diver.[Inventory Type], 
    Diver.[Royalty Code], 
    CORP02WK.Style, 
    CORP02WK.Color, 
    CORP02WK.[Beginning Balance], 
    CORP02WK.[Shipped Quantity], 
    CORP02WK.[Open Balance], 
    CORP02WK.[Heading Month 1], 
    CORP02WK.[Forecast Month 1], 
    "" AS [PO 1], 
    "" AS [Mo 1, Wk 1], 
    "" AS [Mo 1, Wk 2], 
    "" AS [Mo 1, Wk 3], 
    "" AS [Mo 1, Wk 4], 
    "" AS [Mo 1, Wk 5], 
    CORP02WK.[Receipts Month 1], 
    CORP02WK.[Balance Month 1], 
    [CORP02WK]![Balance Month 1]/[CORP02WK]![Forecast Month 2] AS [Percentage Month 1], 
    CORP02WK.[Forecast Month 2], 
    "" AS [PO 2], 
    "" AS [Mo 2, Wk 1], 
    "" AS [Mo 2, Wk 2], 
    "" AS [Mo 2, Wk 3], 
    "" AS [Mo 2, Wk 4], 
    "" AS [Mo 2, Wk 5], 
    CORP02WK.[Receipts Month 2], 
    CORP02WK.[Balance Month 2], 
    [CORP02WK]![Balance Month 2]/[CORP02WK]![Forecast Month 3] AS [Percentage Month 2], 
    CORP02WK.[Forecast Month 3], 
    "" AS [PO 3], 
    "" AS [Mo 3, Wk 1], 
    "" AS [Mo 3, Wk 2], 
    "" AS [Mo 3, Wk 3], 
    "" AS [Mo 3, Wk 4], 
    "" AS [Mo 3, Wk 5], 
    CORP02WK.[Receipts Month 3], 
    CORP02WK.[Balance Month 3], 
    [CORP02WK]![Balance Month 3]/[CORP02WK]![Forecast Month 4] AS [Percentage Month 3], 
    CORP02WK.[Forecast Month 4], 
    "" AS [PO 4], 
    "" AS [Mo 4, Wk 1], 
    "" AS [Mo 4, Wk 2], 
    "" AS [Mo 4, Wk 3], 
    "" AS [Mo 4, Wk 4], 
    "" AS [Mo 4, Wk 5], 
    CORP02WK.[Receipts Month 4], 
    CORP02WK.[Balance Month 4], 
    [CORP02WK]![Balance Month 4]/[CORP02WK]![Forecast Month 5] AS [Percentage Month 4], 
    CORP02WK.[Forecast Month 5], 
    "" AS [PO 5], 
    "" AS [Mo 5 Wk 1], 
    "" AS [Mo 5 Wk 2], 
    "" AS [Mo 5 Wk 3], 
    "" AS [Mo 5 Wk 4], 
    "" AS [Mo 5 Wk 5], 
    CORP02WK.[Receipts Month 5], 
    CORP02WK.[Balance Month 5], 
    [CORP02WK]![Balance Month 5]/[CORP02WK]![Forecast Month 6] AS [Percentage Month 5], 
    CORP02WK.[Forecast Month 6], 
    "" AS [PO 6], 
    "" AS [Mo 6 Wk 1], 
    "" AS [Mo 6 Wk 2], 
    "" AS [Mo 6 Wk 3], 
    "" AS [Mo 6 Wk 4], 
    "" AS [Mo 6 Wk 5], 
    CORP02WK.[Receipts Month 6], 
    CORP02WK.[Balance Month 6], 
    [CORP02WK]![Balance Month 6]/[CORP02WK]![Forecast Month 7] AS [Percentage Month 6], 
    CORP02WK.[Forecast Month 7], 
    CORP02WK.[Forecast Month 8], 
    WMAWIPSE.[Shade code - table #45], 
    WMAWIPSE.[Cut number], 
    WMAWIPSE.[Cut sequence number], 
    ALP.ALP, 
    WMAWIPSE.[Shop Code Table #26], 
    WMAWIPSE.[Open Qty], 
    "" AS [Rcpt Month], 
    WMAWIPSE.[Original Ship date], 
    WMAWIPSE.[Requested Ship date], 
    WMAWIPSE.[Shipment date], 
    "" AS [Curr Ship], 
    WMAWIPSE.[Warehouse Date], 
    WMAWIPSE.[Ship Via Table #01], 
    WMAWIPSE.[Revised reason code], 
    WMAWIPSE.Comments, 
    [Buying Group].[Buying Groups]
FROM (((((((((CORP02WK 
INNER JOIN WMAWIPSE ON (CORP02WK.Style = WMAWIPSE.Style) AND (CORP02WK.Color = WMAWIPSE.[Color Code Table #25])) 
INNER JOIN Month_Table_2 ON CORP02WK.[Heading Month 2] = Month_Table_2.[Heading Month]) 
INNER JOIN Month_Table_1 ON CORP02WK.[Heading Month 1] = Month_Table_1.[Heading Month]) 
INNER JOIN Month_Table_3 ON CORP02WK.[Heading Month 3] = Month_Table_3.[Heading Month]) 
INNER JOIN Month_Table_4 ON CORP02WK.[Heading Month 4] = Month_Table_4.[Heading Month]) 
INNER JOIN Month_Table_5 ON CORP02WK.[Heading Month 5] = Month_Table_5.[Heading Month]) 
INNER JOIN Month_Table_6 ON CORP02WK.[Heading Month 6] = Month_Table_6.[Heading Month]) 
INNER JOIN Diver ON CORP02WK.Style = Diver.Style) 
LEFT JOIN ALP ON WMAWIPSE.[Cut number] = ALP.[Cut Number]) 
INNER JOIN [Buying Group] ON (CORP02WK.Color = [Buying Group].Color) AND (CORP02WK.Style = [Buying Group].Style)
ORDER BY CORP02WK.[Core Code], CORP02WK.Style, CORP02WK.Color, WMAWIPSE.[Warehouse Date];
